// ---- users
GET http://localhost:8000/user/getAllUsers

###
// --- service
POST http://localhost:8000/service/create
Content-Type: application/json

{
    "service_id": "RSV004",
    "service_name": "Dịch vụ chung",
    "unit": "room",
    "prices": 300000,
    "description": "Gồm: Điện chung (máy giặt, thang máy, hành lang), Vệ sinh, Rác,..."
}
###
GET http://localhost:8000/service/getAllServices
